GET http://localhost:5000/users

###

GET http://localhost:5000/users/61779ebeecd8f4da2291ea23

###

POST http://localhost:5000/users
Content-Type: application/json

{
    "user": "Emmanuel Campuzano Contreras",
    "email": "emmanuelcampu@gmail.com",
    "age": 19
}

###

DELETE http://localhost:5000/users/617a411bfa1e83ee81a13862